# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef33edeeed3b22a3109d617e86996201156fb2e99cbddd92300eb1be3e298f78daef7573ae04a02727fb7ca77e58d04f83bd0a490f8a1343aaf268622b59fc63

test:
  secret_key_base: 9eaedf425795f174994d0881aa4c78f091ee0773811f405ce71710253a812acd697dc0b9fb75959c1cf75701ac0f1a2d2e535936ac3bc8cc546e617b19930238

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
